from __future__ import annotations

from typing import Any, Optional, Protocol

from api.features.rebalancing.models import RebalanceRunData


class IRebalancingRepository(Protocol):
    def get_suggestions(self, mode: Any) -> list[Any]: ...
    def run_rebalancing(self, mode: Any) -> RebalanceRunData: ...
    def get_results(self, mode: Optional[Any], limit: int) -> list[Any]: ...
    def get_risk_budget(self) -> list[Any]: ...
