from __future__ import annotations

from typing import Any, Protocol


class IAlertsRepository(Protocol):
    def list_recent(self, limit: int) -> list[Any]: ...
    def mark_read(self, alert_id: int) -> None: ...
    def generate_target_alerts(self) -> int: ...
    def get_pending_telegram_alerts(self, level_filter: str) -> tuple[list[Any], list[tuple[Any, str]], int, str]: ...
    def record_telegram_logs(self, pending: list[tuple[Any, str]], status: str, error: str | None) -> None: ...
