from __future__ import annotations

from typing import Any, Protocol


class IAlertsRepository(Protocol):
    def list_recent(self, limit: int) -> list[Any]: ...
    def mark_read(self, alert_id: int) -> None: ...
    def generate_target_alerts(self) -> int: ...
