from __future__ import annotations

from typing import Any, Protocol


class IBacktestsRepository(Protocol):
    def run_backtest(self, body: Any) -> Any: ...
    def list_runs(self, limit: int) -> list[Any]: ...
    def get_run(self, run_id: int) -> Any: ...
    def get_decisions(self, run_id: int) -> list[Any]: ...
    def get_positions(self, run_id: int) -> list[Any]: ...
    def get_trades(self, run_id: int) -> list[Any]: ...
