from __future__ import annotations

from typing import Any, Protocol

from api.features.system.models import SystemStatusData


class ISystemRepository(Protocol):
    def get_status_data(self) -> SystemStatusData: ...
    def list_modes(self) -> list[Any]: ...
    def get_mode_info(self, mode: Any) -> Any: ...
    def sync_accounts(self, mode: Any) -> Any: ...
