from __future__ import annotations

from typing import Any, Optional, Protocol


class IDocumentsRepository(Protocol):
    def list_documents(self, type: Optional[str], limit: int) -> list[Any]: ...
    def count_by_type(self) -> dict[str, int]: ...
    def create_document(self, doc: Any) -> Any: ...
    def update_document(self, doc_id: int, doc: Any) -> Any: ...
    def delete_document(self, doc_id: int) -> None: ...
