from tests.unit.score_pipeline.test_semiconductor_sector_asset_scores import test_sector_and_asset_outputs_are_distinct_and_missing_competitive_field_lowers_confidence
def test_raw_feature_candidate_path_stays_non_allocating():test_sector_and_asset_outputs_are_distinct_and_missing_competitive_field_lowers_confidence()
