from tests.unit.score_pipeline.test_semiconductor_market_features import test_market_snapshot_excludes_future_fx_and_marks_base_return_unavailable
def test_fixture_market_pipeline_is_deterministic(): test_market_snapshot_excludes_future_fx_and_marks_base_return_unavailable()
