from tests.unit.score_pipeline.test_semiconductor_shadow_tilt import test_shadow_tilt_is_continuous_and_quality_or_concentration_cannot_increase_it
def test_shadow_tilt_does_not_activate_allocation():test_shadow_tilt_is_continuous_and_quality_or_concentration_cannot_increase_it()
