from tests.backtest.test_semiconductor_fixture_backtest import test_synthetic_two_cycle_backtest_is_deterministic_and_excludes_future_rows
def test_fixture_backtest_pipeline():test_synthetic_two_cycle_backtest_is_deterministic_and_excludes_future_rows()
