from __future__ import annotations

from typing import Any, Protocol


class IAccountsRepository(Protocol):
    def get_accounts(self, mode: Any) -> list[Any]: ...
    def get_account_policies(self) -> list[Any]: ...
    def get_snapshots(self, account_id: int, limit: int) -> list[Any]: ...
    def save_manual_snapshot(self, account_id: int, body: Any) -> Any: ...
    def set_rebalancing_inclusion(self, account_id: int, include: bool) -> bool: ...
    def upsert_holdings_from_rows(self, rows: list[dict]) -> int: ...
    def get_allocation(self) -> list[Any]: ...
